name: "Calibration"
on:
  schedule:
    # Runs every day at 00:00 to ensure everything is still working
    - cron: "0 0 * * *"
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency: calibration

jobs:
  test-calibration:
    name: "Test on Calibration Network"
    runs-on: zondax-runners
    strategy:
      max-parallel: 1
      matrix:
        version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}
      - name: Install yarn
        run: npm install -g yarn
      - name: Install yalc
        run: npm install -g yalc
      - name: Install dependencies
        run: |
          yarn install
          npx playwright install-deps
      - name: Lint
        run: yarn lint
      - name: Format
        run: yarn format
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test:silent
        env:
          NETWORK: "calibration"
          NODE_RPC_URL: ${{ secrets.CALIBRATION_NODE_RPC_URL }}
          NODE_RPC_TOKEN: ${{ secrets.CALIBRATION_NODE_RPC_TOKEN }}
          ACCOUNT_MNEMONIC: ${{ secrets.ACCOUNT_MNEMONIC }}
