name: "Mainnet - Reusable Workflow"
on:
  workflow_call

jobs:
  mainnet_reusable:
    name: "Test on Mainnet Network"
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install yarn
        run: npm install -g yarn
      - name: Install yalc
        run: npm install -g yalc
      - name: Install dependencies
        run: |
          yarn install
          npx playwright install-deps
      - name: Lint
        run: yarn lint
      - name: Format
        run: yarn format
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test:silent
        env:
          NETWORK: "mainnet"
          NODE_RPC_URL: ${{ secrets.MAINNET_NODE_RPC_URL }}
          NODE_RPC_TOKEN: ${{ secrets.MAINNET_NODE_RPC_TOKEN }}
          ACCOUNT_MNEMONIC: ${{ secrets.ACCOUNT_MNEMONIC }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
