name: "Checks"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: "Integrity checks"
    runs-on: "self-hosted"
    strategy:
      matrix:
        version: [16, 18]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}
      - name: Install yarn
        run: npm install -g yarn
      - name: Install yalc
        run: npm install -g yalc
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -y install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev
          yarn install
      - name: Lint
        run: yarn lint
      - name: Format
        run: yarn format
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test:silent
        env:
          NODE_RPC_URL: ${{ secrets.NODE_RPC_URL }}
          NODE_RPC_TOKEN: ${{ secrets.NODE_RPC_TOKEN }}
          ACCOUNT_MNEMONIC: ${{ secrets.ACCOUNT_MNEMONIC }}
          SENDER_ACCOUNT_PATH: ${{ secrets.SENDER_ACCOUNT_PATH }}
          RECEIVER_ACCOUNT_PATH: ${{ secrets.RECEIVER_ACCOUNT_PATH }}
